# Generated by Django 4.0 on 2021-12-23 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_observed_authenticity_article_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='predicted_authenticity',
            new_name='predicted_label',
        ),
    ]
