# Generated by Django 4.0 on 2022-01-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_article_predicted_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
