# Generated by Django 4.0 on 2022-01-04 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'ordering': ('-created_at',)},
        ),
    ]
